default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DB_DEV_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>

production:
  cable:
    <<: *default
    database: <%= ENV['DB_PROD_NAME'] %>
